### ISSUE TITLE
Crear un README.md

### ISSUE THREAD

**Issue by idcmardelplata** [Jose-Simon-Pepe/automaticGTD#1]
Creo que es necesario crear un fichero README.md para poder explicar claramente:

-  [x] Cuales son los objetivos del proyecto.
-  [x] En que etapa de construcción se encuentra actualmente.
-  [x] Cuales son las features que aporta.
-  [ ] Cuales son los proyectos similares y en que se diferencia este del resto.
-  [x] En que casos debería de ser usado y en cuales no
-  [ ] Como utilizar el proyecto.
-  [ ] Comenzar a recibir feedback de la comunidad.

No se que opinas @Jose-Simon-Pepe.

**Comment by Jose-Simon-Pepe** [comment]
Me parece algo sumamente importante, así como el contar con esa to-do list de puntos a considerar.
