### ISSUE TITLE
Simplificar el proceso de instalacion y puesta en marcha del proyecto

### ISSUE THREAD

**Issue by idcmardelplata** [Jose-Simon-Pepe/automaticGTD#2]
Creo que seria buena idea agregar un script para inicial izar la aplicación y que se encargue de algunas tareas comunes en el proyecto, estas tareas pueden ser:

- [ ] Activar un entorno virtual
- [ ] Instalar las dependencias dentro de ese entorno (únicamente para entorno de desarrollo)
- [ ] Ejecutar la aplicación
- [ ] Ejecutar las pruebas unitarias
- [ ] Ejecutar las pruebas de integración
- [ ] Ejecutar las pruebas de aceptación

Esto habré la posibilidad de tener en un único lugar una manera de ejecutar distintas tareas del proyecto.

**Comment by idcmardelplata** [comment]
@Jose-Simon-Pepe  para este issue estaba pensando en usar [pyproject](https://python-poetry.org/docs/pyproject/) (para mantener un listado de todas las dependencias) y alguna tool como [pybuilder](https://pybuilder.io/) para unificar el proceso de building y ejecución de pruebas, ademas nos serviría para generar distintos tipos de paquetes para distintos SO (windows, linux, etc)

**Comment by Jose-Simon-Pepe** [comment]
@idcmardelplata Me hacen sentido los puntos sobre inicializar la app, voy a informarme sobre algunas cuestiones y lo considero para el proyecto. Gracias por eso y por la recomendación de techs!
